name: Build and Push Docker Image of client

on:
  push:
    branches:
      - master
    paths:
      - 'client/Dockerfile'
      - 'client/**'
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom Docker tag name"
        required: false
        default: "manual"
      platforms:
        description: "Platforms to build (comma-separated)"
        required: false
        default: "linux/amd64,linux/arm64"
      push_image:
        description: "Push image to registry?"
        required: false
        default: "true"
        type: boolean

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-client

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag/version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${{ github.event.inputs.custom_tag || 'latest' }}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }} # Add later: linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' && (github.event.inputs.push_image != 'false') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
